### ISSUE TITLE
If config isn't in config file then don't try to do anything

### ISSUE THREAD

**Issue by surminus** [surminus/myosx#7]
If the config file only contains homebrew packages for example, then don't try to do anything else.

**Comment by surminus** [comment]
This happens if something isn't present in the brew config:
```
/Users/lauramartin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/myosx-0.2.1/lib/myosx/homebrew.rb:25:in `block in bundle': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/lauramartin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/myosx-0.2.1/lib/myosx/homebrew.rb:22:in `open'
	from /Users/lauramartin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/myosx-0.2.1/lib/myosx/homebrew.rb:22:in `bundle'
	from /Users/lauramartin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/myosx-0.2.1/lib/myosx/homebrew.rb:35:in `exec'
	from /Users/lauramartin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/myosx-0.2.1/lib/myosx.rb:12:in `initialize'
	from /Users/lauramartin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/myosx-0.2.1/bin/myosx:5:in `new'
	from /Users/lauramartin/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/myosx-0.2.1/bin/myosx:5:in `<top (required)>'
	from /Users/lauramartin/.rbenv/versions/2.3.0/bin/myosx:23:in `load'
	from /Users/lauramartin/.rbenv/versions/2.3.0/bin/myosx:23:in `<main>'
```

**Comment by surminus** [comment]
Resolved in https://github.com/surminus/myosx/commit/e8feb769381df0d290c50d3715bc843f7200d393
